Stp defend play
RoboTeamTwente/roboteam_ai pull request #1078
Opened 2020-05-06 10:01 UTC by jordiluong

Improved defend play

Closes #1073

2020-05-06 10:44 UTC, timovdk commented on src/stp/new_plays/Defend.cpp
> +    }
I would use std::erase_if

2020-05-06 10:50 UTC, timovdk requested changes
Looks good besides my comment.

2020-05-06 10:55 UTC, timovdk commented on src/stp/new_plays/Defend.cpp
> +    }
Oops, std::erase_if is C++20, you should use [this](https://stackoverflow.com/questions/39019806/using-erase-remove-if-idiom) instead. std::erase(std::remove_if())

2020-05-06 15:21 UTC, timovdk approved these changes

2020-05-07 07:20 UTC, RobotJente approved these changes

2020-05-07 07:20 UTC, merged