Feature/stp reflect kick
RoboTeamTwente/roboteam_ai pull request #1134
Opened 2020-06-01 10:40 UTC by timovdk

Reflect kick

2020-06-02 09:06 UTC, rolfvdhulst requested changes
See comments. IMO, most things look neat but don't put a lot of vector calculus on one line because it makes things very hard to read/understand for others

2020-06-02 09:06 UTC, rolfvdhulst commented on src/stp/new_plays/ReflectKick.cpp
> +    }
This will be problematic if the ball ever rolls towards our goal, there will still be an intersection.

2020-06-02 09:06 UTC, rolfvdhulst commented on src/stp/new_plays/ReflectKick.cpp
> +    reflectPosition = field.getTheirGoalCenter() + (reflectPosition - field.getTheirGoalCenter()).stretchToLength((reflectPosition - field.getTheirGoalCenter()).length() + control_constants::CENTER_T
This line is way too long. Just cut it up into multiple lines.

2020-06-02 09:06 UTC, rolfvdhulst commented on src/stp/new_plays/ReflectKick.cpp
> +    reflectPosition = field.getTheirGoalCenter() + (reflectPosition - field.getTheirGoalCenter()).stretchToLength((reflectPosition - field.getTheirGoalCenter()).length() + control_constants::CENTER_T
Especially vector calculus should be easy to read.

2020-06-02 09:06 UTC, rolfvdhulst commented on src/stp/new_plays/ReflectKick.cpp
> +    reflectPosition = field.getTheirGoalCenter() + (reflectPosition - field.getTheirGoalCenter()).stretchToLength((reflectPosition - field.getTheirGoalCenter()).length() + control_constants::CENTER_T
You can even consider making this a function

2020-06-02 09:06 UTC, rolfvdhulst commented on src/stp/new_plays/ReflectKick.cpp
> +    }
Lines are infinite

2020-06-02 09:06 UTC, rolfvdhulst commented on src/stp/new_skills/Kick.cpp
> +            info.getRobot().value()->getAngleDiffToBall() <= control_constants::GO_TO_POS_ANGLE_ERROR_MARGIN * M_PI) {
This seems like a pretty unrelated change. How does Go TO POS affect the kick skill?

2020-06-02 09:06 UTC, rolfvdhulst commented on src/stp/new_tactics/KickAtPos.cpp
> +    return true;
Are you really sure this does not break other tactics?

2020-06-02 09:06 UTC, rolfvdhulst commented on src/stp/new_tactics/KickAtPos.cpp
> +    return true;
Atleast, change the documentation

2020-06-03 07:58 UTC, rttwente approved these changes

2020-06-05 08:06 UTC, HaicoDorenbos requested changes
I cannot accept this PR in this current state, because: 
- A lot of documentation is missing. This is mostly related to class documentation, which is really important, since other software developers can then better understand your code and test is properly.
- At some places there is unnecessary documentation. You should not document overridden methods if that method in the super class is properly documented except if the behaviour of that method does not comply anymore with the specification in the super class (usually a bad practice to have these kind of cases).
- Some coordinates get hard coded. Special locations should be defined in the Field class. Also if you want to get a relative position on the Field then you should create a method in the FieldComputation class for this.
- Be consistent where you use Line, LineSegment or HalfLine. And know the differences between these classes. 

During the team meeting on Wednessday I noticed that the preventive maintenance tasks of earlier PR's will be skipped, because some tasks are delayed and will therefore be worked on after the deadline which means that there is no time left for the preventive maintenance tasks of earlier PR's. Therefore PR's should only be merged once the preventive maintenance is also completed for that PR, otherwise you will create technical debt for future teams.

2020-06-05 08:06 UTC, HaicoDorenbos commented on include/roboteam_ai/stp/new_plays/ReflectKick.h
> +class ReflectKick : public Play {
In most cases you do not document overriden methods if they a properly documented in the superclass. Except of course if the behaviour really changes. But make sure that class documentation is not missing.

2020-06-05 08:06 UTC, HaicoDorenbos commented on include/roboteam_ai/stp/new_roles/BallReflecter.h
> +class BallReflecter : public Role {
Class documentation is missing

2020-06-05 08:06 UTC, HaicoDorenbos commented on include/roboteam_ai/stp/new_tactics/PositionAndAim.h
> +class PositionAndAim : public Tactic {
Where is the class documentation?

2020-06-05 08:06 UTC, HaicoDorenbos commented on include/roboteam_ai/stp/new_tactics/PositionAndAim.h
> +    PositionAndAim();
This method should properly be documented.

2020-06-05 08:06 UTC, HaicoDorenbos commented on src/stp/new_plays/ReflectKick.cpp
> +        intersection = Line(ball->getPos(), ball->getPos() + ball->getVelocity()).intersects(Line(passPosition, field.getTheirGoalCenter()));
Make sure that you select the right line type. Consider using LineSegment or HalfLine instead:
- Line: Has infinite length in both directions.
- HalfLine: Has a starting point and infinite length in one direction.
- LineSegment: Has a start and end point, which means it has finite length

2020-06-05 08:06 UTC, HaicoDorenbos commented on src/stp/new_plays/ReflectKick.cpp
> +    stpInfos["offender_2"].setPositionToMoveTo(Vector2(field.getFieldLength() / 4, -field.getFieldWidth() / 4));
This is not the way how to encode positions in the field. Using this technique you will hard code coordinates. Consider making a constant for this location stored in the Field class or consider to create a method in the FieldComputation class that returns relative positions.

2020-06-05 08:06 UTC, HaicoDorenbos commented on src/stp/new_plays/ReflectKick.cpp
> +    stpInfos["midfielder_3"].setPositionToMoveTo(Vector2(field.getFieldLength() / 8, 0.0));
Do not hard code coordinates this way. It makes things a lot less clear and enforces you to use a certain coordinate system.

2020-06-05 11:04 UTC, closed without merging