Refactor of STP architecture
RoboTeamTwente/roboteam_ai pull request #1234
Opened 2021-05-27 15:19 UTC by JaroKuiken

### Summary of changes
List of all the biggest changes:
- 'Refactor' STP back to its original vision, i.e. smaller, more modular Plays and removed certain unused or useless classes.
- Architecture for a more advanced scoring system than hard coded numbers.
- Give some Plays smarter calculations and decision making (this can never be finished of course, but some improvements)
- Any calculation that is made more than once has been generalized and moved to a computation module to avoid duplicate code.
- Smarter calculations for positioning and passing have been made and moved to a computation module.
- Approach that the Dealer uses to deal out Roles to robots has been corrected.
- Start of architecture to store information between Plays, such as which robot was selected to receive a pass from the previous Play. Not used right now, should be used when things like a Passing Play are separated into a Passing and a Receiving Play.
- Renamed Invariants to Evaluations as it seemed like a more understandable name.
- Probably some other small things i'm forgetting.

2021-06-01 19:48 UTC, Floris-Hoek commented on src/stp/plays/offensive/AttackingPass.cpp
> +        }
Both conditions are the same. In the original play there was a boolean that determined which of the two would be picked. It was changed here: https://github.com/RoboTeamTwente/roboteam_ai/pull/1234/commits/10c718e59fb69653e9199b1f34610a0a46d0d6e2

2021-06-01 19:48 UTC, Floris-Hoek commented on src/stp/tactics/passive/Walling.cpp
> +        skillStpInfo.setPidType(PIDType::KEEPER_INTERCEPT);
No idea if another PIDType would be better but to me it seems more logical that a player PIDType would be chosen

2021-06-01 19:48 UTC, Floris-Hoek commented on src/stp/computations/GoalComputations.cpp
> +    LineSegment &GoalComputations::getLongestSegment(std::vector<LineSegment> &openSegments) {
Can't
std::vector<LineSegment> &openSegments 
be:
const std::vector<LineSegment> &openSegments
?

2021-06-01 19:48 UTC, Floris-Hoek commented on src/stp/computations/GoalComputations.cpp
> +    LineSegment &GoalComputations::getLongestSegment(std::vector<LineSegment> &openSegments) {
As it was before

2021-06-01 19:48 UTC, Floris-Hoek commented on src/stp/computations/PositionComputations.cpp
> +        auto w = world->getWorld().value();
w is only used once

2021-06-01 19:48 UTC, Floris-Hoek commented on src/stp/computations/PositionComputations.cpp
> +            LineSegment ball2GoalLine = LineSegment(ballPos, field.getOurGoalCenter());
Can be placed outside of the for loop

2021-06-01 19:48 UTC, Floris-Hoek commented on src/stp/computations/PositionComputations.cpp
> +                auto posX = field.getOurGoalCenter().x < 0 ? -4.3 : 4.3;
Hardcoded values

2021-06-01 19:48 UTC, Floris-Hoek commented on src/utilities/Dealer.cpp
> +
Not entirely sure what is happening here but is this the best way of removing the elements?

2021-06-01 19:48 UTC, Floris-Hoek commented on src/ApplicationManager.cpp
>  void ApplicationManager::decidePlay(world::World *_world) {
Is it checked before decidePlay is called if _world has a value? Otherwise possible segfault problem in playevaluator.update(_world) (line 168)

2021-06-01 19:48 UTC, Floris-Hoek commented on src/ApplicationManager.cpp
> +    playChecker.update(_world, playEvaluator);
Maybe needed in the future but right now world is not used in playChecker

2021-06-06 19:19 UTC, Yuhanun requested changes, later dismissed

2021-06-06 19:19 UTC, Yuhanun commented on include/roboteam_ai/stp/Play.hpp
> +    uint8_t getLastScore();
const pls

2021-06-06 19:19 UTC, Yuhanun commented on include/roboteam_ai/stp/Play.hpp
> +    uint8_t getLastScore();
const pls

2021-06-06 19:19 UTC, Yuhanun commented on include/roboteam_ai/stp/Play.hpp
> +    bool shouldEndPlay() noexcept;
This feels just insanely hacky

2021-06-06 19:19 UTC, Yuhanun commented on include/roboteam_ai/stp/PlayChecker.hpp
> +    void update(world::World* world, PlayEvaluator& playEvaluator) noexcept;
Why does this need this?

2021-06-06 19:19 UTC, Yuhanun commented on include/roboteam_ai/stp/PlayDecider.hpp
> +    Play *decideBestPlay(std::vector<Play *> plays, PlayEvaluator& playEvaluator) noexcept;
Same for this

2021-06-06 19:19 UTC, Yuhanun commented on include/roboteam_ai/stp/PlayChecker.hpp
> +    void update(world::World* world, PlayEvaluator& playEvaluator) noexcept;
PlayEvaluator already contains a world*

2021-06-06 19:19 UTC, Yuhanun commented on include/roboteam_ai/stp/evaluations/global/BallCloseToThemGlobalEvaluation.h
> +#include "include/roboteam_ai/stp/evaluations/BaseEvaluation.h"
this include.

2021-06-06 19:19 UTC, Yuhanun commented on include/roboteam_ai/stp/evaluations/global/BallCloseToUsGlobalEvaluation.h
> +#include "include/roboteam_ai/stp/evaluations/BaseEvaluation.h"
leading `include/`

2021-06-06 19:19 UTC, Yuhanun commented on include/roboteam_ai/stp/evaluations/global/BallClosestToUsGlobalEvaluation.h
> +#include "include/roboteam_ai/stp/evaluations/BaseEvaluation.h"
leading include/

2021-06-06 19:19 UTC, Yuhanun commented on include/roboteam_ai/stp/evaluations/global/BallGotShotGlobalEvaluation.h
> +#include "include/roboteam_ai/stp/evaluations/BaseEvaluation.h"
include/

2021-06-06 19:19 UTC, Yuhanun commented on include/roboteam_ai/stp/evaluations/global/BallMovesSlowGlobalEvaluation.h
> +#include "include/roboteam_ai/stp/evaluations/BaseEvaluation.h"
include/

2021-06-06 19:19 UTC, Yuhanun commented on include/roboteam_ai/stp/evaluations/global/BallOnOurSideGlobalEvaluation.h
> +#include "include/roboteam_ai/stp/evaluations/BaseEvaluation.h"
everywhere.

2021-06-06 19:19 UTC, Yuhanun commented on include/roboteam_ai/stp/plays/ReflectKick.h
> +    uint8_t score(PlayEvaluator &playEvaluator) noexcept override;
I still dont' get why a Play needs the evaluator?...

2021-06-06 19:19 UTC, Yuhanun commented on include/roboteam_ai/stp/plays/contested/GetBallPossession.h
> +   protected:
is this the first protected: in the codebase

2021-06-06 19:19 UTC, Yuhanun commented on include/roboteam_ai/stp/plays/defensive/DefendPass.h
> +    void calculateInfoForScoredRoles(world::World*) noexcept override {};
```suggestion
    void calculateInfoForScoredRoles(world::World* world) noexcept override {};
```

2021-06-06 19:19 UTC, Yuhanun commented on include/roboteam_ai/stp/roles/passive/Waller.h
> +    class Waller : public Role {
Some documentation for what a Waller is would be nice

2021-06-06 19:19 UTC, Yuhanun commented on src/stp/Play.cpp
> +                std::to_string(previousPlayInfos->begin()->second.robotID.value_or(-1)));
```suggestion
        if (!previousPlayInfos->empty()) {
            RTT_DEBUG(
                std::to_string(previousPlayInfos->begin()->second.robotID.value_or(-1)));
        }
```

2021-06-06 19:19 UTC, Yuhanun commented on src/stp/Play.cpp
> +                    // TODO Is this still used/usable?
TODO here, maybe fix before merge?

2021-06-06 19:19 UTC, Yuhanun commented on src/stp/PlayDecider.cpp
> +        return *std::max_element(plays.begin(), plays.end(), [&](auto &largest, auto &play) { return largest->score(playEvaluator) < play->score(playEvaluator); });
This could be expensive computation, the largest->sscore, maybe it's better to get an 

std::vector<std::pair<Play*, uint8_t>> where it's play, score so you only compute it once per play?

2021-06-06 19:19 UTC, Yuhanun commented on src/stp/computations/PositionComputations.cpp
> +                                                                            : calculatedScores[position];
```suggestion
        gen::PositionScores &scores = calculatedScores[position];
```

2021-06-06 19:19 UTC, Yuhanun commented on src/stp/computations/PositionComputations.cpp
> +                                                                            : calculatedScores[position];
Same thing

2021-06-06 19:19 UTC, Yuhanun commented on src/stp/computations/PositionComputations.cpp
> +        }
```suggestion
        std::vector<double> enemyDistances;
        auto& them = world->getWorld()->getThem();
        enemyDistances.reserve(them.size());
        for (auto &enemyRobot : them) {
            enemyDistances.push_back(point.dist(enemyRobot->getPos()));
        }
```

2021-06-06 19:19 UTC, Yuhanun commented on src/stp/computations/PositionComputations.cpp
> +        std::vector<double> enemyAnglesToBallvsPoint;
reserve.

2021-06-06 19:19 UTC, Yuhanun commented on src/stp/computations/PositionComputations.cpp
> +        std::vector<double> enemyAnglesToBallvsPoint;
reserve.

2021-06-06 19:19 UTC, Yuhanun commented on src/stp/computations/PositionComputations.cpp
> +                for (int i = 0; i < amountDefenders; i++) {
reserve?

2021-06-06 19:19 UTC, Yuhanun commented on src/stp/evaluations/game_states/BallPlacementThemGameStateEvaluation.cpp
> +    return GameStateManager::getCurrentGameState().getStrategyName() == "ball_placement_them" ? stp::control_constants::FUZZY_TRUE : stp::control_constants::FUZZY_FALSE;
what?...

2021-06-06 19:19 UTC, Yuhanun commented on src/stp/evaluations/game_states/BallPlacementUsGameStateEvaluation.cpp
> +    return GameStateManager::getCurrentGameState().getStrategyName() == "ball_placement_us" ? stp::control_constants::FUZZY_TRUE : stp::control_constants::FUZZY_FALSE;
why?

2021-06-06 19:19 UTC, Yuhanun commented on src/stp/evaluations/game_states/FreeKickThemGameStateEvaluation.cpp
> +    return GameStateManager::getCurrentGameState().getStrategyName() == "free_kick_them" ? stp::control_constants::FUZZY_TRUE : stp::control_constants::FUZZY_FALSE;
why?

2021-06-06 19:19 UTC, Yuhanun commented on src/stp/evaluations/game_states/HaltGameStateEvaluation.cpp
> +    return GameStateManager::getCurrentGameState().getStrategyName() == "halt" ? stp::control_constants::FUZZY_TRUE : stp::control_constants::FUZZY_FALSE;
why

2021-06-06 19:19 UTC, Yuhanun commented on src/stp/evaluations/game_states/FreeKickUsGameStateEvaluation.cpp
> +    return GameStateManager::getCurrentGameState().getStrategyName() == "free_kick_us" ? stp::control_constants::FUZZY_TRUE : stp::control_constants::FUZZY_FALSE;
why

2021-06-06 19:19 UTC, Yuhanun commented on src/stp/evaluations/game_states/KickOffThemGameStateEvaluation.cpp
> +    return GameStateManager::getCurrentGameState().getStrategyName() == "kickoff_them" ? stp::control_constants::FUZZY_TRUE : stp::control_constants::FUZZY_FALSE;
guys why do we have edge cases for this stuff?...

2021-06-06 19:19 UTC, Yuhanun commented on src/stp/plays/PlayTemplate.cpp
> +                std::make_unique<role::Waller>(role::Waller("waller_2"))};
```suggestion
                std::make_unique<role::Keeper>("keeper"),
                std::make_unique<role::Formation>("role_0"),
                std::make_unique<role::Formation>("role_1"),
                std::make_unique<role::Formation>("role_2"),
                std::make_unique<role::Formation>("role_3"),
                std::make_unique<role::Formation>("role_4"),
                std::make_unique<role::Formation>("role_5"),
                std::make_unique<role::Formation>("role_6"),
                std::make_unique<role::Waller>("waller_0"),
                std::make_unique<role::Waller>("waller_1"),
                std::make_unique<role::Waller>("waller_2")};
```

2021-06-06 19:19 UTC, Yuhanun commented on src/stp/roles/Keeper.cpp
> +#include "include/roboteam_ai/stp/tactics/active/KickAtPos.h"
why?

2021-06-06 19:19 UTC, Yuhanun commented on src/stp/roles/Keeper.cpp
> +#include "include/roboteam_ai/stp/tactics/active/KickAtPos.h"
Like the /include/roboteam_ai part

2021-06-06 19:19 UTC, Yuhanun commented on src/world/FieldComputations.cpp
> +    if (point.x < field.getTopLeftCorner().x) fixedPoint.x = field.getTopLeftCorner().x + margin; //Left
These lines are quite long no?

2021-06-07 12:40 UTC, Floris-Hoek commented
There is currently somewhere a bug (I guess somewhere in the Dealer) that causes the Keeper Role to be given to the robot closest to the goal and not to the specified ID number.

2021-06-07 13:09 UTC, Floris-Hoek commented
These are the plays that do it correctly:

ID 0 = keeper:
Attacking Pass
Attack
Defend Shot
Defend Pass
Free Kick Them
Get Ball Possession
Get Ball Risky
Reflect Kick
Generic Pass



And the ones that do not:
ID 0 != keeper:
Defensive Formation
Aggresive Formation
Ball Placement Us
Ball Placement Them
Penalty Them Prepare
Penalty Us Prepare
Penalty Them
Penalty Us
Kick Off Us Prepare
Kick Off Them Prepare
Kick Off Us
Kick Off Them

2021-06-08 11:03 UTC, Floris-Hoek commented
> These are the plays that do it correctly:
> 
> ID 0 = keeper:
> Attacking Pass
> Attack
> Defend Shot
> Defend Pass
> Free Kick Them
> Get Ball Possession
> Get Ball Risky
> Reflect Kick
> Generic Pass
> 
> And the ones that do not:
> ID 0 != keeper:
> Defensive Formation
> Aggresive Formation
> Ball Placement Us
> Ball Placement Them
> Penalty Them Prepare
> Penalty Us Prepare
> Penalty Them
> Penalty Us
> Kick Off Us Prepare
> Kick Off Them Prepare
> Kick Off Us
> Kick Off Them

Fixed it

2021-06-14 11:23 UTC, JaroKuiken commented on include/roboteam_ai/stp/plays/ReflectKick.h
> +    uint8_t score(PlayEvaluator &playEvaluator) noexcept override;
Because scoring of plays will be done with the evaluator from now on

2021-06-14 13:25 UTC, JaroKuiken commented on src/stp/evaluations/game_states/BallPlacementThemGameStateEvaluation.cpp
> +    return GameStateManager::getCurrentGameState().getStrategyName() == "ball_placement_them" ? stp::control_constants::FUZZY_TRUE : stp::control_constants::FUZZY_FALSE;
This is the same as before, but different class name

2021-06-14 13:25 UTC, JaroKuiken commented on src/stp/evaluations/game_states/BallPlacementUsGameStateEvaluation.cpp
> +    return GameStateManager::getCurrentGameState().getStrategyName() == "ball_placement_us" ? stp::control_constants::FUZZY_TRUE : stp::control_constants::FUZZY_FALSE;
This is the same as before, but different class name

2021-06-14 13:25 UTC, JaroKuiken commented on src/stp/evaluations/game_states/FreeKickThemGameStateEvaluation.cpp
> +    return GameStateManager::getCurrentGameState().getStrategyName() == "free_kick_them" ? stp::control_constants::FUZZY_TRUE : stp::control_constants::FUZZY_FALSE;
This is the same as before, but different class name

2021-06-14 13:26 UTC, JaroKuiken commented on src/stp/evaluations/game_states/FreeKickUsGameStateEvaluation.cpp
> +    return GameStateManager::getCurrentGameState().getStrategyName() == "free_kick_us" ? stp::control_constants::FUZZY_TRUE : stp::control_constants::FUZZY_FALSE;
This is the same as before, but different class name

2021-06-14 13:26 UTC, JaroKuiken commented on src/stp/evaluations/game_states/HaltGameStateEvaluation.cpp
> +    return GameStateManager::getCurrentGameState().getStrategyName() == "halt" ? stp::control_constants::FUZZY_TRUE : stp::control_constants::FUZZY_FALSE;
This is the same as before, but different class name

2021-06-14 13:27 UTC, JaroKuiken commented on src/stp/evaluations/game_states/KickOffThemGameStateEvaluation.cpp
> +    return GameStateManager::getCurrentGameState().getStrategyName() == "kickoff_them" ? stp::control_constants::FUZZY_TRUE : stp::control_constants::FUZZY_FALSE;
Edge cases?

2021-06-14 13:31 UTC, JaroKuiken commented on include/roboteam_ai/stp/Play.hpp
> +    bool shouldEndPlay() noexcept;
Its not used now, but maybe it shouldnt be used at some point later either. But at least the option is there

2021-06-14 15:33 UTC, merged