Feature/canshoottotarget
RoboTeamTwente/roboteam_ai pull request #253
Opened 2019-04-08 18:54 UTC by mrlukasbos

This is probably useful for passing and detecting passes within trees

2019-04-15 14:49 UTC, rolfvdhulst reviewed
Looks fine, but how does this differ from HasClearshot? Both even call the same clearLine function. Suggest maybe merging those

2019-04-15 15:03 UTC, mrlukasbos commented
Has clearshot specifically only looks at their goal...

2019-04-16 07:37 UTC, rolfvdhulst reviewed
Yes, so it would be identical to setting target to theirGoal in your skill. Feels kind of like redundant c++ to recompile if we change constants to me.

2019-04-16 12:00 UTC, mrlukasbos commented
yes. that other skill can probably be removed and this one should be extended. I prefer doing that later though

2019-04-17 12:16 UTC, ThijsLuttikhuis requested changes
currently not usable without hardcoding the position of the target Vector2

2019-04-17 12:16 UTC, ThijsLuttikhuis commented on roboteam_ai/src/conditions/CanShootToTarget.cpp
> +    if (properties->hasVector2("target")) {
how do you get the target? is it a hardcoded vector2?

2019-04-17 12:16 UTC, ThijsLuttikhuis commented on roboteam_ai/src/conditions/CanShootToTarget.cpp
> +		margin = properties->getDouble("margin");
in passing, the margin is an angle from the shooting robot in stead of a distance to the passline,
maybe change this to the same definition of can shoot to target

2019-04-17 12:16 UTC, ThijsLuttikhuis commented on roboteam_ai/src/conditions/CanShootToTarget.cpp
> +	bool canShoot = control::ControlUtils::clearLine(robot->pos, target, world::world->getWorld(), margin, true);
clearLine is a vague name for a function, on it's own it would mean that you 'clear' the line i.e. delete/reset it.

2019-04-25 12:19 UTC, mrlukasbos commented
I guess this is getting outdated.

2019-04-25 12:19 UTC, closed without merging