Fix/side attacker positioning
RoboTeamTwente/roboteam_ai pull request #306
Opened 2019-04-23 07:21 UTC by RobZelluf

- Improve the claiming of positions by the side attackers.
- Also improve passing and receiving a bit

2019-04-23 12:08 UTC, Barisimre requested changes

2019-04-23 12:08 UTC, Barisimre commented on roboteam_ai/src/coach/OffensiveCoach.cpp
> +    for(auto &sideAttacker : sideAttackers) {
why not just use a set? But I guess if it works it works

2019-04-23 12:08 UTC, Barisimre commented on roboteam_ai/src/skills/Attack.cpp
> +        std::cout << "SUCCESS" << std::endl;
Remove print

2019-04-23 12:08 UTC, Barisimre commented on roboteam_ai/src/skills/Attack.cpp
> +            std::cout << "SHOT" << std::endl;
Remove print

2019-04-23 12:08 UTC, Barisimre commented on roboteam_ai/src/skills/Receive.cpp
> +            std::cout << robot->id << " - " << ball->vel << std::endl;
print

2019-04-23 12:08 UTC, Barisimre commented on roboteam_ai/src/skills/Receive.cpp
> +        std::cout << "Ball deflected!" << std::endl;
print

2019-04-23 12:08 UTC, Barisimre commented on roboteam_ai/src/skills/Receive.cpp
> +    return false;
Okay just use
```
return receiverMissedBall();
```

2019-04-24 07:52 UTC, rolfvdhulst requested changes

2019-04-24 09:05 UTC, rolfvdhulst approved these changes

2019-04-24 09:06 UTC, Barisimre approved these changes

2019-04-24 09:50 UTC, merged