Refactor/skills new world without control
RoboTeamTwente/roboteam_ai pull request #862
Opened 2020-03-06 19:34 UTC by mrlukasbos

2020-03-09 13:11 UTC, Yuhanun commented
I think it's good to merge if you fix the codefactor issues, i trust you in that this works :)

2020-03-10 15:11 UTC, Yuhanun commented
Shouldn't have references to vews

2020-03-10 15:13 UTC, Yuhanun requested changes

2020-03-10 15:13 UTC, Yuhanun commented on include/roboteam_ai/analysis/DecisionMaker.h
> +    PlayStyle getRecommendedPlayStyle(BallPossession possession, int amountOfRobots);
```suggestion
    PlayStyle getRecommendedPlayStyle(BallPossession possession, uint8_t amountOfRobots);
```

2020-03-10 15:13 UTC, Yuhanun commented on include/roboteam_ai/analysis/play-utilities/Play.h
>  #include "functional"
```suggestion
#include <functional>
```

2020-03-10 15:13 UTC, Yuhanun commented on include/roboteam_ai/analysis/play-utilities/invariants/AlwaysFalseInvariant.h
>  #include <include/roboteam_ai/world/Field.h>
```suggestion
#include <world/Field.h>
```

2020-03-10 15:13 UTC, Yuhanun commented on include/roboteam_ai/coach/BallplacementCoach.h
> +
```suggestion

```

2020-03-10 15:13 UTC, Yuhanun commented on include/roboteam_ai/coach/BallplacementCoach.h
> +    Vector2 getBallPlacementAfterPos(const world_new::view::RobotView &robot);
```suggestion
    Vector2 getBallPlacementAfterPos(const world_new::view::RobotView robot);
```

2020-03-10 15:13 UTC, Yuhanun commented on include/roboteam_ai/coach/OffensiveCoach.h
> +#include <include/roboteam_ai/world_new/views/RobotView.hpp>
```suggestion
#include <world_new/views/RobotView.hpp>
```

2020-03-10 15:13 UTC, Yuhanun commented on src/coach/BallplacementCoach.cpp
> +Vector2 BallplacementCoach::getBallPlacementAfterPos(const world_new::view::RobotView &robot) {
```suggestion
Vector2 BallplacementCoach::getBallPlacementAfterPos(const world_new::view::RobotView robot) {
```

2020-03-10 15:13 UTC, Yuhanun commented on include/roboteam_ai/coach/OffensiveCoach.h
> +    void addSideAttacker(const Field &field, const world_new::view::RobotView &robot);
```suggestion
    void addSideAttacker(const Field &field, const world_new::view::RobotView robot);
```

2020-03-10 15:13 UTC, Yuhanun commented on include/roboteam_ai/coach/OffensiveCoach.h
> +    void removeSideAttacker(const world_new::view::RobotView &robot);
```suggestion
    void removeSideAttacker(const world_new::view::RobotView robot);
```

2020-03-10 15:13 UTC, Yuhanun commented on include/roboteam_ai/coach/PassCoach.h
> +    bool validReceiver(const Field &field, const world_new::view::RobotView &passer, const world_new::view::RobotView &receiver, bool freeKick = false);
```suggestion
    bool validReceiver(const Field &field, const world_new::view::RobotView passer, const world_new::view::RobotView receiver, bool freeKick = false);
```

2020-03-10 15:13 UTC, Yuhanun commented on include/roboteam_ai/coach/midfield/MidFieldCoach.h
> +    std::map<int, world_new::view::RobotView> targetRobotsToHarass_new;
```suggestion
    std::map<uint8_t, world_new::view::RobotView> targetRobotsToHarass;
    std::map<uint8_t, world_new::view::RobotView> targetRobotsToHarass_new;
```

2020-03-10 15:13 UTC, Yuhanun commented on include/roboteam_ai/coach/midfield/MidFieldCoach.h
> +    double calculateStandingFreeScore(const Field &field, const Vector2 &position, const world_new::view::RobotView &thisRobot);
```suggestion
    Target getBall(world_new::view::RobotView thisRobot, const world_new::view::RobotView opponent);
    Target standFree(const Field &field, const world_new::view::RobotView thisRobot);
    MidFieldCoach::Target harassRobot(const world_new::view::RobotView thisRobot, const world_new::view::RobotView opponent, HarassType harassType) const;
    Target blockPass(const world_new::view::RobotView thisRobot, const world_new::view::RobotView opponent, const world_new::view::BallView ball) const;
    Vector2 calculateNewRobotPosition(const Field &field, const world_new::view::RobotView thisRobot, Angle targetAngle);
    double calculateStandingFreeScore(const Field &field, const Vector2 &position, const world_new::view::RobotView thisRobot);
```

2020-03-10 15:13 UTC, Yuhanun commented on include/roboteam_ai/coach/midfield/MidFieldCoach.h
> +    void addMidFielder(world_new::view::RobotView &thisRobot);
```suggestion
    void addMidFielder(world_new::view::RobotView thisRobot);
```

2020-03-10 15:13 UTC, Yuhanun commented on include/roboteam_ai/coach/midfield/MidFieldCoach.h
> +    void removeMidFielder(world_new::view::RobotView &thisRobot);
```suggestion
    void removeMidFielder(world_new::view::RobotView thisRobot);
```

2020-03-10 15:13 UTC, Yuhanun commented on include/roboteam_ai/coach/midfield/MidFieldCoach.h
> +    bool validOpponent(const Field &field, const world_new::view::RobotView &opponent);
```suggestion
    bool validOpponent(const Field &field, const world_new::view::RobotView opponent);
```

2020-03-10 15:13 UTC, Yuhanun commented on include/roboteam_ai/coach/midfield/MidFieldCoach.h
> +    world_new::view::RobotView findRobotToHarass(const Field &field, const world_new::view::RobotView &thisRobot);
```suggestion
    world_new::view::RobotView findRobotToHarass(const Field &field, const world_new::view::RobotView thisRobot);
```

2020-03-10 15:13 UTC, Yuhanun commented on include/roboteam_ai/coach/midfield/MidFieldCoach.h
> +    HarassType getHarassType(const world_new::view::RobotView &thisRobot, const world_new::view::RobotView &opponent);
```suggestion
    HarassType getHarassType(const world_new::view::RobotView thisRobot, const world_new::view::RobotView opponent);
```

2020-03-10 15:13 UTC, Yuhanun commented on include/roboteam_ai/coach/midfield/MidFieldCoach.h
> +    Target getTargetPosition(const Field &field, world_new::view::RobotView &thisRobot);
```suggestion
    Target getTargetPosition(const Field &field, world_new::view::RobotView thisRobot);
```

2020-03-10 15:13 UTC, Yuhanun commented on include/roboteam_ai/coach/midfield/MidFieldCoach.h
> +    HarassType getHarassTypeIfOpponentIsOnTheLeft(const world_new::view::RobotView &thisRobot, const world_new::view::BallView &ball, BallPossession &ballPossession,
```suggestion
    HarassType getHarassTypeIfOpponentIsOnTheLeft(const world_new::view::RobotView thisRobot, const world_new::view::BallView ball, BallPossession &ballPossession,
```

2020-03-10 15:13 UTC, Yuhanun commented on include/roboteam_ai/coach/midfield/MidFieldCoach.h
> +    Target &harassSlowRobot(const world_new::view::RobotView &opponent, const HarassType &harassType, Target &target) const;
```suggestion
    Target &harassSlowRobot(const world_new::view::RobotView opponent, const HarassType &harassType, Target &target) const;
```

2020-03-10 15:13 UTC, Yuhanun commented on include/roboteam_ai/coach/midfield/MidFieldCoach.h
> +    Target &harassFastRobot(const world_new::view::RobotView &thisRobot, const world_new::view::RobotView &opponent, Target &target) const;
```suggestion
    Target &harassFastRobot(const world_new::view::RobotView thisRobot, const world_new::view::RobotView opponent, Target &target) const;
```

2020-03-10 15:13 UTC, Yuhanun commented on include/roboteam_ai/coach/midfield/MidFieldCoach.h
> +    bool isRobotAlreadyBeingHarassed(const world_new::view::RobotView &opponent) const;
```suggestion
    bool isRobotAlreadyBeingHarassed(const world_new::view::RobotView opponent) const;
```

2020-03-10 15:13 UTC, Yuhanun commented on include/roboteam_ai/control/ControlUtils.h
> +            robotIsAimedAtPoint(int id, bool ourTeam, const Vector2 &point, const world_new::view::WorldDataView &world,
```suggestion
            robotIsAimedAtPoint(int id, bool ourTeam, const Vector2 &point, const world_new::view::WorldDataView world,
```

2020-03-10 15:13 UTC, Yuhanun commented on include/roboteam_ai/control/ControlUtils.h
> +            static const std::shared_ptr<world::Robot>
prettu sure this one needs to be refactored

2020-03-10 15:13 UTC, Yuhanun commented on include/roboteam_ai/control/PosController.h
> +    RobotCommand controlWithPID(const world_new::view::RobotView &robot, RobotCommand target);
```suggestion
    RobotCommand controlWithPID(const world_new::view::RobotView robot, RobotCommand target);
```

2020-03-10 15:13 UTC, Yuhanun commented on include/roboteam_ai/control/PosController.h
> +    virtual Vector2 calculatePIDs(const world_new::view::RobotView &robot, RobotCommand &target);
```suggestion
    virtual Vector2 calculatePIDs(const world_new::view::RobotView robot, RobotCommand &target);
```

2020-03-10 15:13 UTC, Yuhanun commented on include/roboteam_ai/control/ball-handling/RotateAroundBall.h
>  #include <include/roboteam_ai/utilities/Constants.h>
```suggestion
#include <utilities/Constants.h>
```

2020-03-10 15:13 UTC, Yuhanun commented on include/roboteam_ai/control/ball-handling/RotateWithBall.h
> +#include <include/roboteam_ai/world_new/views/RobotView.hpp>
```suggestion
#include <world_new/views/RobotView.hpp>
```

2020-03-10 15:13 UTC, Yuhanun commented on include/roboteam_ai/control/ball-handling/RotateWithBall.h
> +    RobotCommand getRobotCommand(const world_new::view::RobotView &r, const Vector2 &targetP, const Angle &targetA);
```suggestion
    RobotCommand getRobotCommand(const world_new::view::RobotView r, const Vector2 &targetP, const Angle &targetA);
```

2020-03-10 15:13 UTC, Yuhanun commented on include/roboteam_ai/skills/ActiveStop.h
> +    static Vector2 getPoint(const Field &field, const rtt::world_new::view::BallView &ball, const Vector2 &penaltyPos);
```suggestion
    static Vector2 getOffensiveActivePoint(const Field &field, const rtt::world_new::view::BallView ball);
    static Vector2 getDefensiveActivePoint(const Field &field, const rtt::world_new::view::BallView ball);
    static Vector2 getPoint(const Field &field, const rtt::world_new::view::BallView ball, const Vector2 &penaltyPos);
```

2020-03-10 15:13 UTC, Yuhanun commented on src/analysis/play-utilities/invariants/BallOnOurSideInvariant.cpp
> +    if (!ballOpt.has_value()) return false;
```suggestion
    if (!ballOpt) return false;
```

2020-03-10 15:13 UTC, Yuhanun commented on src/bt/Node.cpp
> +Node::Status Node::tick(rtt::world_new::view::WorldDataView *world, const rtt::ai::world::Field *field) {
```suggestion
Node::Status Node::tick(rtt::world_new::view::WorldDataView world, const rtt::ai::world::Field *field) {
```

2020-03-10 15:13 UTC, Yuhanun commented on src/bt/include/bt/Node.h
> +    virtual Status tick(rtt::world_new::view::WorldDataView* world, const Field *field);
```suggestion
    virtual Status tick(rtt::world_new::view::WorldDataView world, const Field *field);
```

2020-03-10 15:13 UTC, Yuhanun commented on src/bt/include/bt/Node.h
> +    rtt::world_new::view::WorldDataView* world = nullptr;
```suggestion
    rtt::world_new::view::WorldDataView world = nullptr;
```

2020-03-10 15:13 UTC, Yuhanun commented on src/coach/heuristics/CoachHeuristics.cpp
> +    std::set<u_int8_t> idVector;
```suggestion
    std::set<uint8_t> idVector;
```

2020-03-10 15:13 UTC, Yuhanun commented on src/coach/midfield/MidFieldCoach.cpp
> +void MidFieldCoach::addMidFielder(world_new::view::RobotView &thisRobot) {
```suggestion
void MidFieldCoach::addMidFielder(world_new::view::RobotView thisRobot) {
```

2020-03-10 15:13 UTC, Yuhanun commented on src/coach/midfield/MidFieldCoach.cpp
> +MidFieldCoach::Target MidFieldCoach::getTargetPosition(const Field &field, world_new::view::RobotView &thisRobot) {
```suggestion
MidFieldCoach::Target MidFieldCoach::getTargetPosition(const Field &field, world_new::view::RobotView thisRobot) {
```

2020-03-10 15:13 UTC, Yuhanun commented on src/coach/midfield/MidFieldCoach.cpp
> +bool MidFieldCoach::validOpponent(const Field &field, const world_new::view::RobotView &opponent) {
```suggestion
bool MidFieldCoach::validOpponent(const Field &field, const world_new::view::RobotView opponent) {
```

2020-03-10 15:13 UTC, Yuhanun commented on src/coach/midfield/MidFieldCoach.cpp
> +MidFieldCoach::Target MidFieldCoach::blockPass(const world_new::view::RobotView &thisRobot, const world_new::view::RobotView &opponent, const world_new::view::BallView &ball) const {
```suggestion
MidFieldCoach::Target MidFieldCoach::blockPass(const world_new::view::RobotView thisRobot, const world_new::view::RobotView opponent, const world_new::view::BallView ball) const {
```

2020-03-10 15:13 UTC, Yuhanun commented on src/coach/midfield/MidFieldCoach.cpp
> +void MidFieldCoach::removeMidFielder(world_new::view::RobotView &thisRobot) {
```suggestion
void MidFieldCoach::removeMidFielder(world_new::view::RobotView thisRobot) {
```

2020-03-10 15:13 UTC, Yuhanun commented on src/coach/midfield/MidFieldCoach.cpp
> +    MidFieldCoach::Target MidFieldCoach::harassRobot(const world_new::view::RobotView &thisRobot, const world_new::view::RobotView &opponent, HarassType harassType) const {
```suggestion
    MidFieldCoach::Target MidFieldCoach::harassRobot(const world_new::view::RobotView thisRobot, const world_new::view::RobotView opponent, HarassType harassType) const {
```

2020-03-10 15:13 UTC, Yuhanun commented on src/coach/midfield/MidFieldCoach.cpp
> +    MidFieldCoach::Target &MidFieldCoach::harassFastRobot(const world_new::view::RobotView &thisRobot, const world_new::view::RobotView &opponent, MidFieldCoach::Target &target) const {
```suggestion
    MidFieldCoach::Target &MidFieldCoach::harassFastRobot(const world_new::view::RobotView thisRobot, const world_new::view::RobotView opponent, MidFieldCoach::Target &target) const {
```

2020-03-10 15:13 UTC, Yuhanun commented on src/coach/midfield/MidFieldCoach.cpp
> +MidFieldCoach::Target &MidFieldCoach::harassSlowRobot(const world_new::view::RobotView &opponent, const MidFieldCoach::HarassType &harassType, MidFieldCoach::Target &target) const {
```suggestion
MidFieldCoach::Target &MidFieldCoach::harassSlowRobot(const world_new::view::RobotView opponent, const MidFieldCoach::HarassType &harassType, MidFieldCoach::Target &target) const {
```

2020-03-10 15:13 UTC, Yuhanun commented on src/coach/midfield/MidFieldCoach.cpp
> +world_new::view::RobotView MidFieldCoach::findRobotToHarass(const Field &field, const world_new::view::RobotView &thisRobot) {
```suggestion
world_new::view::RobotView MidFieldCoach::findRobotToHarass(const Field &field, const world_new::view::RobotView thisRobot) {
```

2020-03-10 15:13 UTC, Yuhanun commented on src/coach/midfield/MidFieldCoach.cpp
> +bool MidFieldCoach::isRobotAlreadyBeingHarassed(const world_new::view::RobotView &opponent) const {
```suggestion
bool MidFieldCoach::isRobotAlreadyBeingHarassed(const world_new::view::RobotView opponent) const {
```

2020-03-10 15:13 UTC, Yuhanun commented on src/coach/midfield/MidFieldCoach.cpp
> +MidFieldCoach::Target MidFieldCoach::standFree(const Field &field, const world_new::view::RobotView &thisRobot) {
```suggestion
MidFieldCoach::Target MidFieldCoach::standFree(const Field &field, const world_new::view::RobotView thisRobot) {
```

2020-03-10 15:13 UTC, Yuhanun commented on src/coach/midfield/MidFieldCoach.cpp
> +    MidFieldCoach::HarassType MidFieldCoach::getHarassType(const world_new::view::RobotView &thisRobot, const world_new::view::RobotView &opponent) {
```suggestion
    MidFieldCoach::HarassType MidFieldCoach::getHarassType(const world_new::view::RobotView thisRobot, const world_new::view::RobotView opponent) {
```

2020-03-10 15:13 UTC, Yuhanun commented on src/coach/midfield/MidFieldCoach.cpp
> +    MidFieldCoach::HarassType MidFieldCoach::getHarassTypeIfOpponentIsOnTheLeft(const world_new::view::RobotView &thisRobot, const world_new::view::BallView &ball,
```suggestion
    MidFieldCoach::HarassType MidFieldCoach::getHarassTypeIfOpponentIsOnTheLeft(const world_new::view::RobotView thisRobot, const world_new::view::BallView ball,
```

2020-03-10 15:13 UTC, Yuhanun commented on src/coach/midfield/MidFieldCoach.cpp
> +MidFieldCoach::Target MidFieldCoach::getBall(world_new::view::RobotView &thisRobot, const world_new::view::RobotView &opponent) {
```suggestion
MidFieldCoach::Target MidFieldCoach::getBall(world_new::view::RobotView thisRobot, const world_new::view::RobotView opponent) {
```

2020-03-10 15:13 UTC, Yuhanun commented on src/coach/midfield/MidFieldCoach.cpp
> +double MidFieldCoach::calculateStandingFreeScore(const Field &field, const Vector2 &position, const world_new::view::RobotView &thisRobot) {
```suggestion
double MidFieldCoach::calculateStandingFreeScore(const Field &field, const Vector2 &position, const world_new::view::RobotView thisRobot) {
```

2020-03-10 15:13 UTC, Yuhanun commented on src/coach/midfield/MidFieldCoach.cpp
> +Vector2 MidFieldCoach::calculateNewRobotPosition(const Field &field, const world_new::view::RobotView &thisRobot, Angle targetAngle) {
```suggestion
Vector2 MidFieldCoach::calculateNewRobotPosition(const Field &field, const world_new::view::RobotView thisRobot, Angle targetAngle) {
```

2020-03-10 15:13 UTC, Yuhanun commented on src/conditions/Condition.cpp
> +        std::cout << "[Condition::initialize] Warning. Trying to initialize Condition without the robot present" << std::endl;
RTT_WARNING

2020-03-10 15:13 UTC, Yuhanun commented on src/conditions/Condition.cpp
> +        std::cout << "[Condition::initialize] Warning. Trying to initialize Condition without a ball present" << std::endl;
RTT_WARNING

2020-03-10 15:13 UTC, Yuhanun commented on src/conditions/HasClearShot.cpp
> +    if ((Vector2(ball->get()->getPos()) - (*field).getTheirGoalCenter()).length() < FORCED_SHOOTING_DISTANCE) {
```suggestion
    if ((Vector2(ball->get()->getPos()) - field->getTheirGoalCenter()).length() < FORCED_SHOOTING_DISTANCE) {
```

2020-03-10 15:13 UTC, Yuhanun commented on src/conditions/HasClearShot.cpp
> +    if ((Vector2(ball->get()->getPos()) - (*field).getTheirGoalCenter()).length() > MAX_SHOOTING_DISTANCE) {
```suggestion
    if ((Vector2(ball->get()->getPos()) - field->getTheirGoalCenter()).length() > MAX_SHOOTING_DISTANCE) {
```

2020-03-10 15:13 UTC, Yuhanun commented on src/control/ControlUtils.cpp
> +    bool ControlUtils::clearLine(const Vector2 &fromPos, const Vector2 &toPos, const world_new::view::WorldDataView &world, double safeDistanceFactor, bool includeKeeper) {
```suggestion
    bool ControlUtils::clearLine(const Vector2 &fromPos, const Vector2 &toPos, const world_new::view::WorldDataView world, double safeDistanceFactor, bool includeKeeper) {
```

2020-03-10 15:13 UTC, Yuhanun commented on src/control/ControlUtils.cpp
> +bool ControlUtils::robotIsAimedAtPoint(int id, bool ourTeam, const Vector2 &point, const world_new::view::WorldDataView &world, double maxDifference) {
```suggestion
bool ControlUtils::robotIsAimedAtPoint(int id, bool ourTeam, const Vector2 &point, const world_new::view::WorldDataView world, double maxDifference) {
```

2020-03-10 15:13 UTC, Yuhanun commented on src/control/PosController.cpp
> +RobotCommand PosController::controlWithPID(const world_new::view::RobotView &robot, RobotCommand target) {
```suggestion
RobotCommand PosController::controlWithPID(const world_new::view::RobotView robot, RobotCommand target) {
```

2020-03-10 15:13 UTC, Yuhanun commented on src/control/ball-handling/RotateWithBall.cpp
> +RobotCommand RotateWithBall::getRobotCommand(const world_new::view::RobotView &r, const Vector2 &targetP, const Angle &targetA) {
```suggestion
RobotCommand RotateWithBall::getRobotCommand(const world_new::view::RobotView r, const Vector2 &targetP, const Angle &targetA) {
```

2020-03-10 15:13 UTC, Yuhanun commented on src/skills/ActiveStop.cpp
> +Vector2 ActiveStop::getOffensiveActivePoint(const Field &field, const rtt::world_new::view::BallView &ball) {
```suggestion
Vector2 ActiveStop::getOffensiveActivePoint(const Field &field, const rtt::world_new::view::BallView ball) {
```

2020-03-10 15:13 UTC, Yuhanun commented on src/skills/ActiveStop.cpp
> +Vector2 ActiveStop::getDefensiveActivePoint(const Field &field, const rtt::world_new::view::BallView &ball) {
```suggestion
Vector2 ActiveStop::getDefensiveActivePoint(const Field &field, const rtt::world_new::view::BallView ball) {
```

2020-03-10 15:13 UTC, Yuhanun commented on src/skills/ActiveStop.cpp
> +Vector2 ActiveStop::getPoint(const Field &field, const rtt::world_new::view::BallView &ball, const Vector2 &penaltyPos) {
```suggestion
Vector2 ActiveStop::getPoint(const Field &field, const rtt::world_new::view::BallView ball, const Vector2 &penaltyPos) {
```

2020-03-10 15:13 UTC, Yuhanun commented on src/utilities/RobotDealer.cpp
> +                auto ballOpt = world_new::World::instance()->getWorld()->getBall();
```suggestion
                auto ballOpt = world_new::World::instance()->getWorld()->getBall();
```

2020-03-10 15:13 UTC, Yuhanun commented on src/utilities/RobotDealer.cpp
> +                auto ballOpt = world_new::World::instance()->getWorld()->getBall();
```suggestion
                auto ballOpt = world_new::World::instance()->getWorld()->getBall();
```

2020-03-10 15:13 UTC, Yuhanun commented on src/world_new/views/RobotView.cpp
> +robot::RobotControllers &RobotView::getControllers() const noexcept { return World::instance()->getControllersForRobot(get()->getId()); }
```suggestion
robot::RobotControllers &RobotView::getControllers() const noexcept { 
    return World::instance()->getControllersForRobot(get()->getId()); 
}
```

2020-03-10 15:26 UTC, Yuhanun commented on include/roboteam_ai/treeinterp/Leaf.h
>     protected:
```suggestion
```

2020-03-10 15:26 UTC, Yuhanun commented on include/roboteam_ai/treeinterp/Leaf.h
```suggestion
    protected:
```

2020-03-10 15:28 UTC, Yuhanun commented on src/utilities/IOManager.cpp
```suggestion
```

2020-03-10 15:28 UTC, Yuhanun commented on include/roboteam_ai/control/ball-handling/RotateAroundBall.h
```suggestion
```

2020-03-10 15:28 UTC, Yuhanun commented on src/skills/formations/DefendFreeKick.cpp
```suggestion
```

2020-03-10 16:49 UTC, Ratoone approved these changes
Yes, very good. GJ boiz

2020-03-10 16:49 UTC, Yuhanun approved these changes

2020-03-10 17:08 UTC, merged