Updated tactic to have a proper dtor
RoboTeamTwente/roboteam_ai pull request #883
Opened 2020-03-12 11:02 UTC by Yuhanun

Tactic was emitting warnings for not having a virtual dtor

Virtual destructors ensure calling of the proper child class dtor when destroyed, hence crucial for virtual inheritance

2020-03-12 11:26 UTC, timovdk approved these changes

2020-03-12 12:54 UTC, RobotJesse commented on include/roboteam_ai/stp/Tactic.h
> +
```suggestion
```

2020-03-13 01:01 UTC, RobotJente requested changes
Tests fail

2020-03-13 01:05 UTC, Yuhanun commented
Not my code , someone is assigning the state machine

2020-03-16 11:26 UTC, RobotJente approved these changes

2020-03-16 11:26 UTC, merged