Implemented the Harasser role
RoboTeamTwente/roboteam_ai pull request #975
Opened 2020-03-27 10:58 UTC by timovdk

It uses the BlockRobot and Intercept tactics
Closes #974

2020-03-27 13:16 UTC, jordiluong commented on CMakeLists.txt
> +        src/stp/new_roles/Harasser.cpp)
```suggestion
        )
```

2020-03-27 13:17 UTC, jordiluong approved these changes

2020-03-30 10:01 UTC, Ratoone requested changes
Simple and on point. Need just to fix the build. As I see it here, maybe we should also consider additional logic in the role whether it should decide by itself to skip the end tactic? Here it seems possible

2020-03-30 12:07 UTC, timovdk commented
> Simple and on point. Need just to fix the build. As I see it here, maybe we should also consider additional logic in the role whether it should decide by itself to skip the end tactic? Here it seems possible

I think we need to discuss this, since it is not that defined whether we have logic in roles or not and what logic it should be if there should be logic

2020-03-31 12:21 UTC, RobotJente approved these changes

2020-03-31 12:27 UTC, RobotJente approved these changes

2020-03-31 12:27 UTC, merged